on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Testsuite:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 16.0
    - name: llvm-config
      run: llvm-config --version --bindir --libdir
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: python helper.py test --exit-first-failure
