File: Fn*;

Fn = "func" "name" ParamList Block;

Param = "name" [","];
ParamList = "(" {Param} ")";

Block = "{" {Stmt} "}";

Stmt = StmtExpr
     | StmtLet
     | StmtAssign
     | StmtIf;

StmtExpr = Expr ";";
StmtLet = "let" "name" "=" Expr ";";
StmtAssign = "name" "=" Expr ";";
StmtIf = "if" "(" Expr ")" Block {"else" Block};
StmtReturn = "return" [Expr] ";";

Arg = Expr [","];
ArgList = "(" {Arg} ")";

Expr = ExprName
     | ExprLiteral
     | ExprBinary
     | ExprParen
     | ExprCall;
ExprName = "name";
ExprLiteral = "int";
ExprBinary = Expr ("+" | "-" | "*" | "/" | "==" | "!=" | "<" | ">" | "<=" | ">=") Expr;
ExprParen = "(" Expr ")";
ExprCall = "name" ArgList;